WXR\DirectoryBundle\Entity\BaseContact:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        enabled:
            type: boolean
        fullname:
            length: 255
        description:
            type: text
            nullable: true
        phone:
            length: 20
            nullable: true
        fax:
            length: 20
            nullable: true
        mobile:
            length: 20
            nullable: true
        email:
            length: 50
            nullable: true
        website:
            length: 255
            nullable: true
        position:
            type: integer
            gedmo:
                - sortablePosition
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
    oneToOne:
        address:
            targetEntity: Application\WXR\GeoBundle\Entity\Address
            fetch: EAGER
            cascade: [ all ]
            joinColumn:
                name: address_id
                referencedColumnName: id
                onDelete: SET NULL
    lifecycleCallbacks:
        preUpdate: [ onPreUpdate ]
