parameters:

    wxr_directory.contact.class: Application\WXR\DirectoryBundle\Entity\Contact
    wxr_directory.group.class: Application\WXR\DirectoryBundle\Entity\Group

services:

    wxr_directory.contact.manager.default:
        class: WXR\DirectoryBundle\Entity\ContactManager
        arguments: [@doctrine.orm.entity_manager, %wxr_directory.contact.class%]

    wxr_directory.contact.admin:
        class: %wxr_directory.contact.admin.class%
        arguments: [ ~, %wxr_directory.contact.class%, %wxr_directory.contact.admin.controller% ]
        calls:
            - [ setTranslationDomain, [ %wxr_directory.translation_domain% ] ]
            - [ setTemplate, [ edit, WXRGeoBundle:CRUD:edit.html.twig ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_directory
                label: contacts
                label_catalogue: %wxr_directory.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore

    wxr_directory.group.manager.default:
        class: WXR\DirectoryBundle\Entity\GroupManager
        arguments: [@doctrine.orm.entity_manager, %wxr_directory.group.class%]

    wxr_directory.group.admin:
        class: WXR\DirectoryBundle\Admin\Entity\GroupAdmin
        arguments: [ ~, %wxr_directory.group.class%, %wxr_directory.group.admin.controller% ]
        calls:
            - [ setTranslationDomain, [ %wxr_directory.translation_domain% ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_directory
                label: groups
                label_catalogue: %wxr_directory.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore
