parameters:

    wxr_directory.contact.class: WXR\DirectoryBundle\Entity\Contact
    wxr_directory.group.class: WXR\DirectoryBundle\Entity\Group
    wxr_directory.translation_domain: WXRDirectoryBundle

services:

    # Contact

    wxr_directory.contact.manager:
        class: WXR\DirectoryBundle\Entity\ContactManager
        arguments: [@doctrine.orm.entity_manager, %wxr_directory.contact.class%]

    wxr_directory.contact.admin:
        class: WXR\DirectoryBundle\Admin\Entity\ContactAdmin
        arguments: [ ~, WXR\DirectoryBundle\Entity\Contact, SonataAdminBundle:CRUD ]
        calls:
            - [ setTranslationDomain, [ %wxr_directory.translation_domain% ] ]
            - [ setTemplate, [ edit, WXRGeoBundle:CRUD:edit.html.twig ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_directory
                label: contacts
                label_catalogue: %wxr_directory.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore

    # Group

    wxr_directory.group.manager:
        class: WXR\DirectoryBundle\Entity\GroupManager
        arguments: [@doctrine.orm.entity_manager, %wxr_directory.group.class%]

    wxr_directory.group.admin:
        class: WXR\DirectoryBundle\Admin\Entity\GroupAdmin
        arguments: [ ~, WXR\DirectoryBundle\Entity\Group, SonataAdminBundle:CRUD ]
        calls:
            - [ setTranslationDomain, [ %wxr_directory.translation_domain% ] ]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: wxr_directory
                label: groups
                label_catalogue: %wxr_directory.translation_domain%
                label_translator_strategy: sonata.admin.label.strategy.underscore
