WXR\DirectoryBundle\Entity\BaseContact:
    type: mappedSuperclass
    fields:
        enabled:
            type: boolean
        name:
            length: 50
        description:
            type: text
            nullable: true
        phone:
            length: 20
            nullable: true
        mobile:
            length: 20
            nullable: true
        email:
            length: 50
            nullable: true
        website:
            length: 255
            nullable: true
    oneToOne:
        location:
            targetEntity: WXR\GeoBundle\Entity\Location
            fetch: EAGER
            cascade: [ all ]
            joinColumn:
                name: location_id
                referencedColumnName: id
                onDelete: SET NULL
#    manyToOne:
#        group:
#            targetEntity: WXR\GeoBundle\Entity\Group
#            joinColumn:
#                name: group_id
#                referencedColumnName: id
#                onDelete: SET NULL
