WXR\DirectoryBundle\Entity\BaseContact:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        enabled:
            type: boolean
        position:
            type: integer
            gedmo:
                - sortablePosition
        slug:
            length: 255
            gedmo:
                slug: { fields: [ fullname ] }
        fullname:
            length: 255
        description:
            type: text
            nullable: true
        phone:
            length: 20
            nullable: true
        fax:
            length: 20
            nullable: true
        mobile:
            length: 20
            nullable: true
        email:
            length: 50
            nullable: true
        website:
            length: 255
            nullable: true
    oneToOne:
        location:
            targetEntity: WXR\GeoBundle\Entity\Location
            fetch: EAGER
            cascade: [ all ]
            joinColumn:
                name: location_id
                referencedColumnName: id
                onDelete: SET NULL
#    manyToOne:
#        group:
#            targetEntity: WXR\GeoBundle\Entity\Group
#            joinColumn:
#                name: group_id
#                referencedColumnName: id
#                onDelete: SET NULL
