WXR\DirectoryBundle\Entity\Group:
    type: entity
    table: wxr_directory_group
    manyToMany:
        contacts:
            targetEntity: WXR\DirectoryBundle\Entity\Contact
            mappedBy: groups
