WXR\DirectoryBundle\Entity\Group:
    type: entity
    table: wxr_directory_group
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        slug:
            gedmo:
                slug: { fields: [ name ] }
