# Contact

wxr_directory_contact_admin_list:
    pattern: /list
    defaults: { _controller: WXRDirectoryBundle:ContactAdmin:list }

wxr_directory_contact_admin_add:
    pattern: /add
    defaults: { _controller:WXRDirectoryBundle:ContactAdmin:add }

wxr_directory_contact_admin_edit:
    pattern: /edit/{id}
    defaults: { _controller:WXRDirectoryBundle:ContactAdmin:edit }

wxr_directory_contact_admin_delete:
    pattern: /delete/{id}
    defaults: { _controller:WXRDirectoryBundle:ContactAdmin:delete }

# Group

wxr_directory_group_admin_list:
    pattern: /list
    defaults: { _controller: WXRDirectoryBundle:GroupAdmin:list }

wxr_directory_group_admin_add:
    pattern: /add
    defaults: { _controller:WXRDirectoryBundle:GroupAdmin:add }

wxr_directory_group_admin_edit:
    pattern: /edit/{id}
    defaults: { _controller:WXRDirectoryBundle:GroupAdmin:edit }

wxr_directory_group_admin_delete:
    pattern: /delete/{id}
    defaults: { _controller:WXRDirectoryBundle:GroupAdmin:delete }
